name: api_service_wrapper
description: A Flutter wrapper around Dio HTTP client providing unified API service interface with secure token management, functional error handling, and cross-platform support.

version: 1.0.0
publish_to: "https://pub.dartlang.org"

repository: https://github.com/mustafa-fahimi/api_service_wrapper
homepage: https://github.com/mustafa-fahimi/api_service_wrapper
issue_tracker: https://github.com/mustafa-fahimi/api_service_wrapper/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  database_service_wrapper: ^1.0.2
  dio: ^5.9.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
