name: api_service
description: API Service Package.

version: 2.0.0
publish_to: "none"

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  dio: 5.9.0
  flutter:
    sdk: flutter
  fpdart: 1.1.1
  freezed_annotation: 3.1.0

dev_dependencies:
  build_runner: 2.7.1
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.0
