name: api_service
description: API Service Package which is a custom wrapper over the Dio package. It provides a unified interface for making HTTP requests and managing authentication tokens.

version: 2.1.0
publish_to: "none"

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  database_service:
    git:
      url: https://github.com/mustafa-fahimi/database_service.git
      ref: master
  dio: 5.9.0
  flutter:
    sdk: flutter
  fpdart: 1.1.1
  freezed_annotation: 3.1.0

dev_dependencies:
  build_runner: 2.7.1
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.0
