name: api_service
description: API Service Package.

version: 1.1.0
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  very_good_analysis: ^5.0.0+1

flutter: null
