name: api_service
description: API Service Package.

version: 1.2.1
publish_to: "none"

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: 5.8.0+1
  flutter:
    sdk: flutter
  fpdart: 1.1.1
  freezed_annotation: 3.0.0

dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  freezed: 3.0.6
  lint: 2.8.0
